### PR TITLE
Generated infrastructure model

### PR DESCRIPTION
**Pull request by InfraGenie**
**Edited by the author of this repo:**

I've never edited another person's comment on GitHub but I feel like I need to edit this one. It looks like an advertisement for a product where they are adding their service to various open source projects with links to fill out surveys and promote their product. They've also added multiple PRs.

### CODE REVIEW

**Comment by ricardojaferreira** [comment]
Hey Nick. Sorry if this looks like an ad...It isn't... I am trying to show the product and trying to understand if it can be helpful to improve the documentation and architecture diagram of your repo. Please visit the project page and see for yourself (infragenie.eu). This is not commercial software, just a project being developed for a study on software architecture. I hope you have the time to check it and also to answer to the survey.

**Comment by nickjj** [comment]
Thanks but sorry. I'm not trying to be a jerk but your first point of contact was opening 2 duplicate PRs in rapid succession with links to your service and requesting surveys to be filled out, that's why I closed the PRs and edited out your links.

If you wrote out the PR description with an explanation instead of using a template it would have been more well received but as is it looks like a templated response that you plan to use with other projects.

**Comment by ricardojaferreira** [comment]
I understand your point. But we are trying to validate this at scale, and it will be difficult to create every PR manually, but maybe this was our mistake. I will try to change the PR test to make it more understandable. Regarding the two PRs created was because the first one had the wrong links 😓 , sorry for the spam. The survey will help us to understand if this kind of tool is needed and what could be changed to make it more useful. Besides generating the architecture diagram, the tool also has an editor that can be used to improve the diagram and to add other components to plan future changes or simply to make the diagram more complete. 
I will leave the links again here, so you can try it for yourself:
* Editor for your project: [here](https://infragenie.eu/view/?repo=nickjj/docker-django-example&branch=main&readme=false)
* Main page with some extra information: [here](https://infragenie.eu/)
* And if you can, please let us know what you think. Again, this is not a commercial tool, it was developed at the University of Porto, and all the survey results are anonymous. We don't collect any kind of personal data: [Survey](https://forms.gle/23sJB2tMFPovgEcR7)

**Comment by nickjj** [comment]
You could try operating at no scale by creating human connections with folks before bombing the internet with PRs.

Even now it's coming off like your only goal here is to promote your product. You've managed to link your site 3 times in 2 follow up comments and the survey again. Please stop posting in my repos.

**Comment by ricardojaferreira** [comment]
Ok. Sorry about that. It wasn't my intention to bother you in any way. Have a nice day, and sorry again for this cold approach.

**Pull request closed without merging**
